
-- Create Central Pricing Matrix for Hospital Fees
CREATE TABLE IF NOT EXISTS pricing_matrix (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL, -- 'Consultation', 'Procedure', 'Administration'
    item_name TEXT NOT NULL,
    price NUMERIC NOT NULL DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Seed defaults
INSERT INTO pricing_matrix (category, item_name, price) 
SELECT 'Consultation', 'General Consultation', 2500
WHERE NOT EXISTS (SELECT 1 FROM pricing_matrix WHERE item_name = 'General Consultation');

INSERT INTO pricing_matrix (category, item_name, price) 
SELECT 'Consultation', 'Specialist Consultation', 4000
WHERE NOT EXISTS (SELECT 1 FROM pricing_matrix WHERE item_name = 'Specialist Consultation');

INSERT INTO pricing_matrix (category, item_name, price) 
SELECT 'Procedure', 'Wound Dressing', 1500
WHERE NOT EXISTS (SELECT 1 FROM pricing_matrix WHERE item_name = 'Wound Dressing');

INSERT INTO pricing_matrix (category, item_name, price) 
SELECT 'Procedure', 'Suturing', 3000
WHERE NOT EXISTS (SELECT 1 FROM pricing_matrix WHERE item_name = 'Suturing');

INSERT INTO pricing_matrix (category, item_name, price) 
SELECT 'Administration', 'Registration Fee', 500
WHERE NOT EXISTS (SELECT 1 FROM pricing_matrix WHERE item_name = 'Registration Fee');
