-- Create password_change_requests table
CREATE TABLE IF NOT EXISTS password_change_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT NOT NULL,
    current_password TEXT, -- Storing plain text for review as requested by user, though not recommended for production
    new_password TEXT NOT NULL,
    status TEXT DEFAULT 'pending', -- pending, authorized, revoked
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add index for faster lookups
CREATE INDEX IF NOT EXISTS idx_password_change_requests_email ON password_change_requests(user_email);
CREATE INDEX IF NOT EXISTS idx_password_change_requests_status ON password_change_requests(status);

