-- 1. Update Appointment Table for Consultation Fee Gate
ALTER TABLE appointment ADD COLUMN IF NOT EXISTS consultation_fee_paid BOOLEAN DEFAULT FALSE;
ALTER TABLE appointment ADD COLUMN IF NOT EXISTS consultation_fee_amount NUMERIC DEFAULT 0;

-- 2. Update Lab Requests for Payment Gate
ALTER TABLE lab_requests ADD COLUMN IF NOT EXISTS is_paid BOOLEAN DEFAULT FALSE;
ALTER TABLE lab_requests ADD COLUMN IF NOT EXISTS price NUMERIC DEFAULT 0;

-- 3. Create Procedures table if it doesn't exist
CREATE TABLE IF NOT EXISTS procedures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id BIGINT REFERENCES appointment(appoid),
    pid BIGINT REFERENCES patient(pid),
    docid BIGINT,
    procedure_name TEXT,
    is_paid BOOLEAN DEFAULT FALSE,
    price NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Create treatment_bundles table if not exists (for lab pricing/catalog)
-- This might already exist, but ensuring it has price if needed
ALTER TABLE lab_catalog ADD COLUMN IF NOT EXISTS price NUMERIC DEFAULT 0;
